### ISSUE TITLE
GDPR Tracking

### ISSUE THREAD

**Issue by zafai** [mautic/mautic-wordpress#123]
We would like to use Mautic Wordpress Plugin with Borlabs.

In the config we found this information "wpmautic_send()" but when sending it with borlabs after the user clicked yes nothing is happening.

Does wpmautic_send() still work or do we need to call something else?

Thank you

**Comment by shulard** [comment]
Hello @zafai !

Are you talking about the `wpmautic_send()` javascript function ?

If so you can view the code here: https://github.com/mautic/mautic-wordpress/blob/main/wpmautic.php#L150

I guess that's still the correct way to go. If you want to be GDPR compliant, you must load the mtc.js script manually whenever the user accepted cookies and trackers.

If you don't get any error when executing the function then this means that the mtc.js file is loaded and that the `mt(...)` call can be performed. If you are using some adblockers, all the Mautic tracking events are blocked by default (ublock origin on Firefox for example). Maybe that's the issue here ?

I'll take a look at the network tab in the browser and the JavaScript console to check if an error or blocking event have popped.

**Comment by shulard** [comment]
You're welcome ^^

I close this one now
