### ISSUE TITLE
Support the new javascript tracker

### ISSUE THREAD

**Issue by amit777** [mautic/mautic-wordpress#25]
Mautic 1.4 introduce a javascript tracker.  This would be awesome to add as well.

**Comment by funnyprinter** [comment]
Just had the same thought!

**Comment by npracht** [comment]
Hi @dongilbert,

I have the feeling you have updated the plugin in the view that it integrates the JS instead of the tracking pixel.
But if you go on: https://wordpress.org/plugins/wp-mautic/ i see that the plugin has not been updated since.. 9months.

Would you also update WordPress page documentation + version?
We (the community) does not have rights for that.

Thanks a lot,

N.

**Comment by BurlesonBrad** [comment]
@npracht the plugin is still using the 1x1 pixel.  Open your site incognito, view source, and search for this:

`mtracking.gif?`

**Comment by npracht** [comment]
Hi @BurlesonBrad,

I agree and i think it should use the script now :-)

**Comment by isleshocky77** [comment]
Looks like this was addressed in 840162

However, there has been no new tag, version bump, or release to wordpress.org/plugins or wpackagist.org.  
See #38

**Comment by shulard** [comment]
Hello,

I'm going to work on the wp.org plugin directory release asap. If you want to stay up to date, take a look at #44.

Since this was addressed in the latest commits, I'll close that issue for the moment.
