### ISSUE TITLE
Mautic Wordpress Plugin and Progressive Profiling

### ISSUE THREAD

**Issue by wheresmylunch** [mautic/mautic-wordpress#33]
Using shortcode on wordpress WP-Mautic plugin and appears that progressive profiling does not work.

Revert to iframe coding and all is working again. So.... need to be aware of this if you want to use this great new feature.

**Comment by abooster** [comment]
@wheresmylunch Yep. I also just came to the same conclusion. 
We seem to have been testing the same thing at the same time! :) 
Using embedding a Mautic page via iframes works OK, 
but it brings its own set of problems. 
Right now, I've just discovered this: 
If I need to use custom JavaScript on a Mautic page (and I have to use it on a Mautic page because I have to embed the Mautic page via iframe), then I am able to insert the JS snippet once and that's it! 
If you come back later wanting to edit ANYTHING on that Mautic page, YOU CAN'T! 

I'm suspecting it's because this bloody Froala editor is messing things up. 
Gosh, how much I'd like to get rid of this Froala shit! 
How can we get rid of this broken Froala shit? It is always causing problems! 
It won't let you do anything with your HTML.

**Comment by abooster** [comment]
So, the only way I can currently "edit" a Mautic page with a custom JavaScript snippet, is to DELETE that page altogether and create a new one. 
What a great way of "editing" a page! :(

**Comment by shulard** [comment]
Hello !

We have published a new [plugin release](https://wordpress.org/plugins/wp-mautic/) available on the WordPress repository.

Is this issue still valid with the latest Mautic updates ?

**Comment by shulard** [comment]
Close this issue because of inactivity.
