### ISSUE TITLE
Failed to execute 'write' on 'Document'

### ISSUE THREAD

**Issue by vesper8** [mautic/mautic-wordpress#61]
No idea why I'm getting this error but would sure appreciate some help.

Don't have any blockers enabled. Using the latest version of the plugin 2.0.3. Using the latest wordpress core.

I added the base url to my mautic instance. I've rebuilt the form caches. Using Mautic 2.8.0 (not 2.8.1)

I've added the tracking to the header and am adding the shortcode for the form near the bottom of my page and am getting this error

```
Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.
```

Any ideas?

Thanks!

**Comment by rc125** [comment]
Same issue here! My forms don't load because this.

`Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.
(anonymous) @ generate.js?id=1:1`

generate.js: https://mautic.even3.com.br/form/generate.js?id=1

Wordpress: https://blog.even3.com.br/

**Comment by vesper8** [comment]
The error is ultimately caused by the "async" part that is generated by the wordpress plugin

```
<script type="text/javascript" src="https://mautic.mydomain.com/form/generate.js?id=1" async="async"></script>
```

I solved my case by simply not using the proposed shortcode from the wordpress plugin and instead insert the above script tag but without the 'async'

I could have also loaded the "postscribe" plugin 
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/postscribe/2.0.8/postscribe.min.js"></script>
```

and then modified the javascript code to replace "document.write" by postscribe

I guess this would have also worked. But anyway the wordpress plugin should give more control over what tag is generated, and should give the option to generate html instead of javascript maybe too?

**Comment by HectorPN** [comment]
I got the same errors.

But apparently could be fixed?

https://stackoverflow.com/questions/32261556/how-to-load-third-party-javascript-tag-asynchronously-which-has-document-write

> 

Document.write will not work from async script because document is already loaded when script starts working.

But you can do this:

document.body.innerHTML = document.body.innerHTML + '<h1>Some HTML</h1>';

>

**Comment by shulard** [comment]
Hello Guys, the latest version fix that error (v2.0.4). It also have been published on WordPress.org repository.

**Comment by shulard** [comment]
For the moment I've just removed the "async" as a quick fix but relying on document.write is not the best thing to do here... The better way is to update the Mautic form generator script to don't use that method then update the WordPress plugin...

**Comment by shulard** [comment]
The wordpress.org support thread has also been updated : https://wordpress.org/support/topic/not-possible-to-write-into-a-document-from-an-asynchronously-loaded-externally/
