### ISSUE TITLE
net::ERR_BLOCKED_BY_RESPONSE

### ISSUE THREAD

**Issue by marsanla** [mautic/mautic-wordpress#66]
Hi i am having this error, since i updated the plugin.

`POST https://mautic.example.com/form/submit?formId=1 net::ERR_BLOCKED_BY_RESPONSE`

and in my CORS of the app i have this:
<img width="772" alt="captura de pantalla 2017-06-20 a las 13 22 18" src="https://user-images.githubusercontent.com/1122550/27330892-8853d504-55bb-11e7-8815-a52d1dbe31aa.png">

UPDATE: there is a relate question [here](https://www.mautic.org/community/index.php/7744-problem-on-form-redirection-wordpress/0)

**Comment by shulard** [comment]
This issue is really strange... It doesn't seems related to the WordPress plugin because the form is displayed and the response is blocked directly by Mautic.

Have you opened an issue on the mautic/mautic repository ? Can you post the headers of the POST request and the response to help ?

**Comment by shulard** [comment]
Hello @marsanla,

Is this issue still valid ?

**Comment by inhies** [comment]
I'm having this problem now as well after reinstalling mautic. It was fine before, but I reinstalled to try and fix some problems and now this happens. Note that when I reinstalled I did everything the same as the first time, I didnt change where I got mautic or what it was intalled to. I'm using the bitnami lamp stack with the mautic module on amazon lightsail.

**Comment by inhies** [comment]
Upon further digging, a big part of the problem was apache setting the X-Frame-Options header. I added this to my httpd.conf `Header set X-Frame-Options "ALLOW-FROM https://mywordpress.site"` and it has fixed mautic forms on my blog, however forms rendered using CF7 Mautic Extention still throw an error.

**Comment by shulard** [comment]
Hello,

If your Apache configuration defines the `X-Frame-Options` header you must allow your website to embed iframes...

More details here : https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options

Maybe after your reinstall, the apache version was upgraded or default configuration as changed but it's not directly related to Mautic installation or configuration.

To avoid that kind of errors, you must use the JavaScript embed instead of the iframe one. On the latest plugin version we use the JS within the form embed shortcode.

There is already an issue on the Mautic repository regarding that header : mautic/mautic#4005

For the CF7 Mautic Extension, I'll check a look on the WordPress repository. It's not an official extension and we aren't in charge of it... Maybe the best way to have support is declare a ticket on the WordPress.org forum section : https://wordpress.org/support/plugin/cf7-mautic-extention

**Comment by shulard** [comment]
Just another point about your CF7 problem. If you get an error when the form is rendered, it's not Mautic related but if you got an error when you submit the form, can you get error details and add it in this issue on in a new issue in the cf7 plugin repository : https://github.com/amimoto-ami/cf7-mautic

**Comment by ikabraham** [comment]
I'm using mautic plugin 2.2.1 with Wordpress and I reeceived the errors listed below:
XMLHttpRequest cannot load https://site.com/services/mtc/event. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.site.com' is therefore not allowed access.
mtracking.gif Failed to load resource: net::ERR_BLOCKED_BY_ADBLOCKER
(index):1 Refused to display 'https://site.com/services/form/submit?formId=1' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
site.com/services/form/submit?formId=1 Failed to load resource: net::ERR_BLOCKED_BY_RESPONSE

Additionally, the site is listed in CORS.

**Comment by DmitrysXYZ** [comment]
Hi

I’m thinking of making it load the data with JSON OR .py OR XML

because i found this problem more for videos on youtube

example

ERROR LOAD https://www.youtube.com/watch?v=8OBfr46Y0cQ

ok load : https://www.youtube.com/embed/8OBfr46Y0cQ ( embed/

will there be a way from my own server in a subfolder to do a API ?

example: test.com/api/embed/

I know that this is for our safety in not accepting external links so easily but a solution must be found by the community

Another solution is on the page where we invite a code to automatically pass a key

example: test.com/test.php?=gssrfwrfdgf reload auto refresh hash key
