### ISSUE TITLE
can one use the user fields of mautic as wordpress shortcodes 

### ISSUE THREAD

**Issue by Amandeepdubey** [mautic/mautic-wordpress#82]
if i want to display the name of the visiotr who may have filled up the mautic form earlier , 
can i do that using the shortcodes ?
is there a way to pull the user fields inside wordpress as shortcodes ?

**Comment by shulard** [comment]
Hello,

Actually it's not possible since the extension only inject the tracking code and other scripts with some configuration. We don't interact directly with Mautic to retrieve some data.

There is an open issue #62 regarding the API integration. I really need some help about it because I haven't enough time these day to work on it...

**Comment by shulard** [comment]
I close this one since the solution is to implement the api manipulation on your side.
