### ISSUE TITLE
No release for a year?

### ISSUE THREAD

**Issue by ecotechie** [mautic/mautic-wordpress#87]
Hi, I see there have constantly been commits on this repo, but last release was on late 2017. Any reason why? The last updated date on WordPress.org shows to be over a year ago, but there is constant development happening. Doesn't look very good on the plugin page.

![image](https://user-images.githubusercontent.com/11607383/53669091-c13ffd00-3c2a-11e9-96f7-b8192bc0c9f4.png)

**Comment by shulard** [comment]
Hello @ecotechie !

You are right, there wasn't any release for about a year on that project and I'm sorry about that. The only commits that have been added to GitHub are about checking compatibility with upcoming WordPress versions. Those commits doesn't involved any code change or new features which deserve a new release.

From a more personal point of view, I'm the one who is responsible maintaining that repository. When I started working on it I was a freelancer and I took about one day per week to work on Open Source projects. Since march 2018, I joined a company and I can't take enough time to push this project forward.

Since OSS really matters to me (and because some others reasons), I decided to leave the company and go back to my self-employed position. This change will done on June 2019.

I'm afraid that before June, the work on that reposition will move slowly. By the way, if you have some time to work on it or new feature idea, I'll be glad to count new contributors on that plugin. Doing code review and merging pull requests is less time consuming than developing the whole stuff myself.
