### ISSUE TITLE
Forms, Focus, etc. won't display when on some browsers.

### ISSUE THREAD

**Issue by VonAden** [mautic/mautic-wordpress#93]
I have been using the plugin for only a few months now. It has seemed to work great! However, I have had a few customers call me up and say that the forms aren't working. I thought that was just an issue with their computer, till today I added a focus and went to test in on Google and Safari and it didn't work. I have also found that non of my forms work either.

I have done a little more testing and have found that only Firefox on Ubuntu actually will allow my forms or focus.

Has this come up or has anyone seen similar issues?

**Comment by shulard** [comment]
Hello,

I'm not sure this is currently related to the plugin, because this plugin is "just" a tiny wrapper about javascript tag injection but I'll be glad to try helping :wink:.

Currently there was no similar issue encountered by other users... I think that the Firefox on Ubuntu is your default browser ? Are you logged in to Mautic in that browser ?

Sometimes the injected contents don't behave the same way when you are logged to Mautic or not. Can you share an URL where the content is not displayed ?

**Comment by AlbanL74fr** [comment]
When they no show, is there any error in the console?
It ever happened to me at times where Mautic was... busy... high CPU, so error 504 in console with error gateaway.

**Comment by VonAden** [comment]
@shulard 
I thought it was strange because it had been working great. The site I am using it on right now is: [www.bsi-cc.com/repair-or-replacement/](url)
I had been using it on other page on this site but with this issue have gone back to the java scrip from mautic.
The Firefox is my default browser and I have tried both being logged into mautic and not logged in. Both ways it still populates. But if I go to any other browser, on any computer (including the Ubuntu), it does not populate.

@AlbanL74fr 
These are the errors I get on Chrome, but they aren't there on Firefox.
![Repair From Google Chrome](https://user-images.githubusercontent.com/44656037/64029750-75e7a800-cb02-11e9-88af-1027bbd909a9.png)

**Comment by AlbanL74fr** [comment]
Search on Google for this error. It may be your SSL certificate installed on your website that has expired

**Comment by VonAden** [comment]
@AlbanL74fr 
Thanks, I didn't ketch that the site I have mautic on needs an updated ssl. So I took the s out of the web address and it works just fine.
